msd_admin_homepage:
    pattern:  /
    defaults: { _controller: MSDAdminBundle:Default:index }

msd_admin_user_edit:
    pattern: /user/edit/{userId}
    defaults: { _controller: MSDAdminBundle:User:edit, userId: 0 }

msd_admin_user_delete:
    pattern: /user/delete/{userId}
    defaults: { _controller: MSDAdminBundle:User:delete }

msd_admin_user_lock:
    pattern: /user/lock/{userId}
    defaults: { _controller: MSDAdminBundle:User:lock }

msd_admin_user_unlock:
    pattern: /user/unlock/{userId}
    defaults: { _controller: MSDAdminBundle:User:unlock }

msd_admin_user_manage_connections:
    pattern: /user/connection/manage/{userId}
    defaults: { _controller: MSDAdminBundle:User:manageConnections }

msd_admin_user_manage_roles:
    pattern: /user/roles/edit/{userId}
    defaults: { _controller: MSDAdminBundle:User:manageRoles }

msd_admin_user_edit_connection:
    pattern: /user/connection/edit/{userId}
    defaults: { _controller: MSDAdminBundle:User:editConnection }

msd_admin_user_connection_check:
    pattern: /user/connection/check
    defaults: { _controller: MSDAdminBundle:User:checkConnection }

msd_admin_user_connection_delete:
    pattern: /user/connection/delete
    defaults: { _controller: MSDAdminBundle:User:deleteConnection }