parameters:
#    msd_admin.example.class: MSD\AdminBundle\Example

services:
#    msd_admin.example:
#        class: %msd_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
