msd_user_homepage:
    pattern:  /
    defaults: { _controller: MSDUserBundle:Default:index }

login:
    pattern: /login
    defaults: { _controller: MSDUserBundle:Default:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout
    defaults: { _controller: MSDUserBundle:Default:logout }