parameters:
#    msd_user.example.class: MSD\UserBundle\Example

services:
#    msd_user.example:
#        class: %msd_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
