parameters:
#    msd_user.example.class: MSD\UserBundle\Example

services:
#    msd_user.example:
#        class: %msd_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    msd.form.type.msd_user:
        class: "MSD\UserBundle\Form\Settings\UserType"
        tags:
            - { name: form.type, alias: msd_user }
