parameters:
#    msd_user.example.class: MSD\UserBundle\Example
    msd.entity_manager_factory.class: MSD\UserBundle\Entity\Manager\FactoryService

services:
#    msd_user.example:
#        class: %msd_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    msd.entity_manager_factory:
        class: %msd.entity_manager_factory.class%
        arguments: [ @security.context ]
