parameters:
#    msd_core.example.class: MSD\CoreBundle\Example
    msd.db_connection.class: Doctrine\DBAL\Connection
    msd.db_connection.factory.class: MSD\CoreBundle\Database\Connection\FactoryService
    msd.twig.menu_builder_extension.class: MSD\CoreBundle\Twig\Extension\MenuBuilder

services:
#    msd_core.example:
#        class: %msd_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    msd.db_connection:
        class: %msd.db_connection.class%
        factory_class: %msd.db_connection.factory.class%
        factory_method: getConnection
        arguments: [ @service_container ]
    msd.twig.menu_builder_extension:
        class: %msd.twig.menu_builder_extension.class%
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }
    kernel.listener.msd_request_change_connection:
        class: MSD\CoreBundle\EventListener\RequestEventListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: changeConnection }
        calls:
            - [setContainer, ["@service_container"]]
    kernel.listener.msd_request_change_db:
        class: MSD\CoreBundle\EventListener\RequestEventListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: changeDatabase }
        calls:
            - [setContainer, ["@service_container"]]
    kernel.listener.msd_request_change_table:
        class: MSD\CoreBundle\EventListener\RequestEventListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: changeTable }
        calls:
            - [setContainer, ["@service_container"]]
